image: node:15

pipelines:
    default:
        -   step:
                name: Build and Deploy
                script:
                    - apt-get update
                    - apt-get install -y zip
                    - node -v
                    - npm -v
                    - npm install
                    - npm run build
                    - zip -r build.zip build/

    deployment:
        -   provider: sftp
            username: $SFTP_USERNAME
            password: $SFTP_PASSWORD
            server: 104.248.167.80
            remote_path: /var/www/app
            local_path: build.zip
            pipeline: default
